// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//
//    var finHubFinancials = FinHubFinancials.FromJson(jsonString);

namespace SocialStock.Financials
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class FinHubFinancials
    {
        [JsonProperty("metric", NullValueHandling = NullValueHandling.Ignore)]
        public Metric Metric { get; set; }

        [JsonProperty("metricType", NullValueHandling = NullValueHandling.Ignore)]
        public string MetricType { get; set; }

        [JsonProperty("series", NullValueHandling = NullValueHandling.Ignore)]
        public Series Series { get; set; }

        [JsonProperty("symbol", NullValueHandling = NullValueHandling.Ignore)]
        public string Symbol { get; set; }
    }

    public partial class Metric
    {
        [JsonProperty("10DayAverageTradingVolume", NullValueHandling = NullValueHandling.Ignore)]
        public double? The10DayAverageTradingVolume { get; set; }

        [JsonProperty("13WeekPriceReturnDaily", NullValueHandling = NullValueHandling.Ignore)]
        public double? The13WeekPriceReturnDaily { get; set; }

        [JsonProperty("26WeekPriceReturnDaily", NullValueHandling = NullValueHandling.Ignore)]
        public double? The26WeekPriceReturnDaily { get; set; }

        [JsonProperty("3MonthAverageTradingVolume", NullValueHandling = NullValueHandling.Ignore)]
        public double? The3MonthAverageTradingVolume { get; set; }

        [JsonProperty("52WeekHigh", NullValueHandling = NullValueHandling.Ignore)]
        public double? The52WeekHigh { get; set; }

        [JsonProperty("52WeekHighDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? The52WeekHighDate { get; set; }

        [JsonProperty("52WeekLow", NullValueHandling = NullValueHandling.Ignore)]
        public double? The52WeekLow { get; set; }

        [JsonProperty("52WeekLowDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? The52WeekLowDate { get; set; }

        [JsonProperty("52WeekPriceReturnDaily", NullValueHandling = NullValueHandling.Ignore)]
        public double? The52WeekPriceReturnDaily { get; set; }

        [JsonProperty("5DayPriceReturnDaily", NullValueHandling = NullValueHandling.Ignore)]
        public double? The5DayPriceReturnDaily { get; set; }

        [JsonProperty("assetTurnoverAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? AssetTurnoverAnnual { get; set; }

        [JsonProperty("assetTurnoverTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? AssetTurnoverTtm { get; set; }

        [JsonProperty("beta", NullValueHandling = NullValueHandling.Ignore)]
        public double? Beta { get; set; }

        [JsonProperty("bookValuePerShareAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? BookValuePerShareAnnual { get; set; }

        [JsonProperty("bookValuePerShareQuarterly", NullValueHandling = NullValueHandling.Ignore)]
        public double? BookValuePerShareQuarterly { get; set; }

        [JsonProperty("bookValueShareGrowth5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? BookValueShareGrowth5Y { get; set; }

        [JsonProperty("capitalSpendingGrowth5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? CapitalSpendingGrowth5Y { get; set; }

        [JsonProperty("cashFlowPerShareAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? CashFlowPerShareAnnual { get; set; }

        [JsonProperty("cashFlowPerShareTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? CashFlowPerShareTtm { get; set; }

        [JsonProperty("cashPerSharePerShareAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? CashPerSharePerShareAnnual { get; set; }

        [JsonProperty("cashPerSharePerShareQuarterly", NullValueHandling = NullValueHandling.Ignore)]
        public double? CashPerSharePerShareQuarterly { get; set; }

        [JsonProperty("currentDividendYieldTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? CurrentDividendYieldTtm { get; set; }

        [JsonProperty("currentEv/freeCashFlowAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? CurrentEvFreeCashFlowAnnual { get; set; }

        [JsonProperty("currentEv/freeCashFlowTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? CurrentEvFreeCashFlowTtm { get; set; }

        [JsonProperty("currentRatioAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? CurrentRatioAnnual { get; set; }

        [JsonProperty("currentRatioQuarterly", NullValueHandling = NullValueHandling.Ignore)]
        public double? CurrentRatioQuarterly { get; set; }

        [JsonProperty("dividendGrowthRate5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? DividendGrowthRate5Y { get; set; }

        [JsonProperty("dividendPerShare5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? DividendPerShare5Y { get; set; }

        [JsonProperty("dividendPerShareAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? DividendPerShareAnnual { get; set; }

        [JsonProperty("dividendYield5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? DividendYield5Y { get; set; }

        [JsonProperty("dividendYieldIndicatedAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? DividendYieldIndicatedAnnual { get; set; }

        [JsonProperty("dividendsPerShareTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? DividendsPerShareTtm { get; set; }

        [JsonProperty("ebitdPerShareTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? EbitdPerShareTtm { get; set; }

        [JsonProperty("ebitdaCagr5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? EbitdaCagr5Y { get; set; }

        [JsonProperty("ebitdaInterimCagr5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? EbitdaInterimCagr5Y { get; set; }

        [JsonProperty("epsBasicExclExtraItemsAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsBasicExclExtraItemsAnnual { get; set; }

        [JsonProperty("epsBasicExclExtraItemsTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsBasicExclExtraItemsTtm { get; set; }

        [JsonProperty("epsExclExtraItemsAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsExclExtraItemsAnnual { get; set; }

        [JsonProperty("epsExclExtraItemsTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsExclExtraItemsTtm { get; set; }

        [JsonProperty("epsGrowth3Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsGrowth3Y { get; set; }

        [JsonProperty("epsGrowth5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsGrowth5Y { get; set; }

        [JsonProperty("epsGrowthQuarterlyYoy", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsGrowthQuarterlyYoy { get; set; }

        [JsonProperty("epsGrowthTTMYoy", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsGrowthTtmYoy { get; set; }

        [JsonProperty("epsInclExtraItemsAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsInclExtraItemsAnnual { get; set; }

        [JsonProperty("epsInclExtraItemsTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsInclExtraItemsTtm { get; set; }

        [JsonProperty("epsNormalizedAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? EpsNormalizedAnnual { get; set; }

        [JsonProperty("focfCagr5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? FocfCagr5Y { get; set; }

        [JsonProperty("grossMargin5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? GrossMargin5Y { get; set; }

        [JsonProperty("grossMarginAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? GrossMarginAnnual { get; set; }

        [JsonProperty("grossMarginTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? GrossMarginTtm { get; set; }

        [JsonProperty("inventoryTurnoverAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? InventoryTurnoverAnnual { get; set; }

        [JsonProperty("inventoryTurnoverTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? InventoryTurnoverTtm { get; set; }

        [JsonProperty("longTermDebt/equityAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? LongTermDebtEquityAnnual { get; set; }

        [JsonProperty("longTermDebt/equityQuarterly", NullValueHandling = NullValueHandling.Ignore)]
        public double? LongTermDebtEquityQuarterly { get; set; }

        [JsonProperty("marketCapitalization", NullValueHandling = NullValueHandling.Ignore)]
        public long? MarketCapitalization { get; set; }

        [JsonProperty("monthToDatePriceReturnDaily", NullValueHandling = NullValueHandling.Ignore)]
        public double? MonthToDatePriceReturnDaily { get; set; }

        [JsonProperty("netIncomeEmployeeAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public long? NetIncomeEmployeeAnnual { get; set; }

        [JsonProperty("netIncomeEmployeeTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? NetIncomeEmployeeTtm { get; set; }

        [JsonProperty("netInterestCoverageAnnual")]
        public object NetInterestCoverageAnnual { get; set; }

        [JsonProperty("netInterestCoverageTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? NetInterestCoverageTtm { get; set; }

        [JsonProperty("netMarginGrowth5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? NetMarginGrowth5Y { get; set; }

        [JsonProperty("netProfitMargin5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? NetProfitMargin5Y { get; set; }

        [JsonProperty("netProfitMarginAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? NetProfitMarginAnnual { get; set; }

        [JsonProperty("netProfitMarginTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? NetProfitMarginTtm { get; set; }

        [JsonProperty("operatingMargin5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? OperatingMargin5Y { get; set; }

        [JsonProperty("operatingMarginAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? OperatingMarginAnnual { get; set; }

        [JsonProperty("operatingMarginTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? OperatingMarginTtm { get; set; }

        [JsonProperty("payoutRatioAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? PayoutRatioAnnual { get; set; }

        [JsonProperty("payoutRatioTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? PayoutRatioTtm { get; set; }

        [JsonProperty("pbAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? PbAnnual { get; set; }

        [JsonProperty("pbQuarterly", NullValueHandling = NullValueHandling.Ignore)]
        public double? PbQuarterly { get; set; }

        [JsonProperty("pcfShareTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? PcfShareTtm { get; set; }

        [JsonProperty("peBasicExclExtraTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? PeBasicExclExtraTtm { get; set; }

        [JsonProperty("peExclExtraAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? PeExclExtraAnnual { get; set; }

        [JsonProperty("peExclExtraHighTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? PeExclExtraHighTtm { get; set; }

        [JsonProperty("peExclExtraTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? PeExclExtraTtm { get; set; }

        [JsonProperty("peExclLowTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? PeExclLowTtm { get; set; }

        [JsonProperty("peInclExtraTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? PeInclExtraTtm { get; set; }

        [JsonProperty("peNormalizedAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? PeNormalizedAnnual { get; set; }

        [JsonProperty("pfcfShareAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? PfcfShareAnnual { get; set; }

        [JsonProperty("pfcfShareTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? PfcfShareTtm { get; set; }

        [JsonProperty("pretaxMargin5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? PretaxMargin5Y { get; set; }

        [JsonProperty("pretaxMarginAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? PretaxMarginAnnual { get; set; }

        [JsonProperty("pretaxMarginTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? PretaxMarginTtm { get; set; }

        [JsonProperty("priceRelativeToS&P50013Week", NullValueHandling = NullValueHandling.Ignore)]
        public double? PriceRelativeToSP50013Week { get; set; }

        [JsonProperty("priceRelativeToS&P50026Week", NullValueHandling = NullValueHandling.Ignore)]
        public double? PriceRelativeToSP50026Week { get; set; }

        [JsonProperty("priceRelativeToS&P5004Week", NullValueHandling = NullValueHandling.Ignore)]
        public double? PriceRelativeToSP5004Week { get; set; }

        [JsonProperty("priceRelativeToS&P500Ytd", NullValueHandling = NullValueHandling.Ignore)]
        public double? PriceRelativeToSP500Ytd { get; set; }

        [JsonProperty("psAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? PsAnnual { get; set; }

        [JsonProperty("psTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? PsTtm { get; set; }

        [JsonProperty("ptbvAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? PtbvAnnual { get; set; }

        [JsonProperty("ptbvQuarterly", NullValueHandling = NullValueHandling.Ignore)]
        public double? PtbvQuarterly { get; set; }

        [JsonProperty("quickRatioAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? QuickRatioAnnual { get; set; }

        [JsonProperty("receivablesTurnoverAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? ReceivablesTurnoverAnnual { get; set; }

        [JsonProperty("receivablesTurnoverTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? ReceivablesTurnoverTtm { get; set; }

        [JsonProperty("revenueEmployeeAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public long? RevenueEmployeeAnnual { get; set; }

        [JsonProperty("revenueEmployeeTTM", NullValueHandling = NullValueHandling.Ignore)]
        public long? RevenueEmployeeTtm { get; set; }

        [JsonProperty("revenueGrowth3Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? RevenueGrowth3Y { get; set; }

        [JsonProperty("revenueGrowth5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? RevenueGrowth5Y { get; set; }

        [JsonProperty("revenueGrowthQuarterlyYoy", NullValueHandling = NullValueHandling.Ignore)]
        public double? RevenueGrowthQuarterlyYoy { get; set; }

        [JsonProperty("revenueGrowthTTMYoy", NullValueHandling = NullValueHandling.Ignore)]
        public double? RevenueGrowthTtmYoy { get; set; }

        [JsonProperty("revenuePerShareAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? RevenuePerShareAnnual { get; set; }

        [JsonProperty("revenuePerShareTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? RevenuePerShareTtm { get; set; }

        [JsonProperty("revenueShareGrowth5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? RevenueShareGrowth5Y { get; set; }

        [JsonProperty("roaRfy", NullValueHandling = NullValueHandling.Ignore)]
        public double? RoaRfy { get; set; }

        [JsonProperty("roaa5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? Roaa5Y { get; set; }

        [JsonProperty("roae5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? Roae5Y { get; set; }

        [JsonProperty("roaeTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? RoaeTtm { get; set; }

        [JsonProperty("roeRfy", NullValueHandling = NullValueHandling.Ignore)]
        public double? RoeRfy { get; set; }

        [JsonProperty("roeTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? RoeTtm { get; set; }

        [JsonProperty("roi5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? Roi5Y { get; set; }

        [JsonProperty("roiAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? RoiAnnual { get; set; }

        [JsonProperty("roiTTM", NullValueHandling = NullValueHandling.Ignore)]
        public double? RoiTtm { get; set; }

        [JsonProperty("tangibleBookValuePerShareAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? TangibleBookValuePerShareAnnual { get; set; }

        [JsonProperty("tangibleBookValuePerShareQuarterly", NullValueHandling = NullValueHandling.Ignore)]
        public double? TangibleBookValuePerShareQuarterly { get; set; }

        [JsonProperty("tbvCagr5Y", NullValueHandling = NullValueHandling.Ignore)]
        public double? TbvCagr5Y { get; set; }

        [JsonProperty("totalDebt/totalEquityAnnual", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalDebtTotalEquityAnnual { get; set; }

        [JsonProperty("totalDebt/totalEquityQuarterly", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalDebtTotalEquityQuarterly { get; set; }

        [JsonProperty("yearToDatePriceReturnDaily", NullValueHandling = NullValueHandling.Ignore)]
        public double? YearToDatePriceReturnDaily { get; set; }
    }

    public partial class Series
    {
        [JsonProperty("annual", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, Annual[]> Annual { get; set; }

        [JsonProperty("quarterly", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, Annual[]> Quarterly { get; set; }
    }

    public partial class Annual
    {
        [JsonProperty("period", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? Period { get; set; }

        [JsonProperty("v", NullValueHandling = NullValueHandling.Ignore)]
        public double? V { get; set; }
    }

    public partial class FinHubFinancials
    {
        public static FinHubFinancials FromJson(string Financials) => JsonConvert.DeserializeObject<FinHubFinancials>(Financials, SocialStock.Financials.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this FinHubFinancials self) => JsonConvert.SerializeObject(self, SocialStock.Financials.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
